### PR TITLE
updating dependency specs and release ID

### PR DESCRIPTION
**Pull request by CritiqalPete**
node package-lock and podfile for
node @22.2.0
npm @10.8.1
react-native-cli  @2.0.1
react-native  @0.72.14

Getting this error on Android:
error Unable to resolve module use-sync-external-store/shim/with-selector from /Users/Pete/AmericaScores-CoachApp/node_modules/react-redux/lib/index.js: use-sync-external-store/shim/with-selector could not be found within the project or in these directories:
  node_modules/react-redux/node_modules
  node_modules

### CODE REVIEW

**Comment by CritiqalPete** [comment]
@za-zohaib attempting to prep for a release by verifying a planned update of node deps. Works OK on iOS but not Android. Maybe if you simply apply the same changes to your next PR, everything will fall into place.

**Comment by CritiqalPete** [comment]
review and cherry-pick dependency updates or merge and go from there, whichever is easier

**Comment by za-zohaib** [comment]
Looking at it. Thanks

**Review by za-zohaib — APPROVED** [review]

**Comment by za-zohaib** [comment]
@CritiqalPete The issue is fixed in thos [PR ](https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/pull/502)

**Pull request merged**
