### PR TITLE
Fix/sessions attendance list

### PR DESCRIPTION
**Pull request by lautirozen**
- Fixed the list on the sessions and attendance screens. Before, refreshing on IOS did not work. Related issue (https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/issues/390).
- Fixed text input not opening the keyboard on the teams screen. Related issue (https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/issues/425).
- Added automatic keyboard hiding when users tap continue on login. Related issue (https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/issues/406).
- Fixed the loading animation when submitting a help request in the help section. Related issue (https://github.com/AmericaSCORESBayArea/AmericaScores-CoachApp/issues/406).

### CODE REVIEW

**Comment by CritiqalPete** [comment]
Great! Will build and review. Inviting others to try as well since there are a lot of things we can check here. @nglover53 ?

**Comment by AaronFlore** [comment]
👍 Built and tested the features on an iPhone 15 pro with IOS 17 and didn't encounter any bugs.

**Comment by CritiqalPete** [comment]
Thanks! @AaronFlore can you share what version npm, react-native and pod you used? Might be helpful for a few of us.

**Review by CritiqalPete — APPROVED** [review]
### PASSED basic testing
**on Android** Pixel_3a_API_34_extension_level_7_arm64-v8a(AVD) - 14
npm 10.3.0
react-native 0.72.10

on iOS iPhone SE Emulator with iOS 15.5 (lowest support target presently)
Pod 1.13.0 (required pod install + pod update)

**Comment by CritiqalPete** [comment]
thanks @lautirozen setting this release to 20.5 on all platforms

**Pull request merged**
