### PR TITLE
Feature/ added coach name in header #484

### PR DESCRIPTION
**Pull request by za-zohaib**
### Task Completed

- Added Coach Name on profile screen header
- removed coach name form profile screen

### Tested on simulator
Iphone 15 pro max (ios 17.4)
looks stable

### CODE REVIEW

**Comment by za-zohaib** [comment]
@CritiqalPete confilts are resolved, you can approve and merge.

**Comment by za-zohaib** [comment]
@CritiqalPete were you able to get a design regarding the profile screen we discussed. "My Profile" appearing on profile page header is looking nice so we decied to get it reworked through designer once.

**Review by CritiqalPete — APPROVED** [review]
tested on iOS simulator. OK to merge

**Comment by CritiqalPete** [comment]
image

**Pull request merged**
