### PR TITLE
Testing Updates to Firebase Tags

### PR DESCRIPTION
**Pull request by nglover53**
Testing small updates to two analytics files before proceeding with further updates to Firebase components and event names

### CODE REVIEW

**Review by CritiqalPete — COMMENTED** [review]
looks good. Ready to test

**Review by CritiqalPete — APPROVED** [review]
ready for merge

**Comment by CritiqalPete** [comment]
@nglover53 getting an error when I run a login test:
"[ReferenceError: Property 'region' doesn't exist]"

normally I would have completed this test without merging to master but I got into a situation with my own working branch.
I will comment this line out and see what happens.

**Comment by nglover53** [comment]
Just making a note region did not exist in the file I edited. My fault I believe I ran debug on one file and not the other upon further inspection.

**Pull request merged**
